### ISSUE TITLE
Feature request: match Tailwind color strings to color values

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [fabiospampinato/vscode-highlight#127]
I wanted to have a regex like the `color configuration` but for Tailwind colors like `bg-green-500` and so on. Technically I could do this by having a separate regex for every color and shade but this would end up with a lot (100+) of regexes.

I thought I could be smart and do something like `$1[$2]` but had no way to actually access a .json file with the mapped values.

My feature request is for vscode-highlight to in some way support things like $1[$2] where the key accesses a file/config or something. 

An example .json file with the colors is here: https://gist.github.com/henrikvilhelmberglund/2c234d0593be41a3d81c7c43e1541364

**Comment by fabiospampinato** [comment]
Cool idea but this seems too specific to add 🤔 with multiple cursors in your editor you should be able to produce the necessary configuration in very little time. The main advantage that I can see is that your solution other than resulting in a cleaner configuration would also scan the input string ~once, rather than once for each color, which may be significant if one has enough colors to match.

**Comment by henrikvilhelmberglund** [comment]
My settings.json file is already pretty enormous so it's fine I guess, it seems fast enough too.
I made a small js program to generate the regexes (? regexi?) which can be found here: https://gist.github.com/henrikvilhelmberglund/430c412d9e758d5391f237e385432b93
I noticed some things like border-t etc are missing but this is how you could approach it at least.
Thanks for the response!
