### ISSUE TITLE
Order of regexes

### ISSUE THREAD

**Issue by guidoselva** [fabiospampinato/vscode-highlight#29]
Your extension is really useful, I like it!

But I have a suggestion to improve it: it seems that the regexes are applied to the document in no particular order (because of the unordered object properties in JS, I guess). So if some regexes are in conflict with each other, there is no way to apply precedence.
For example I may want to highlight "FIXME" in red (regex 1), but not when it is enclosed in double quotes (that I highlight in green with regex 2). With your current settings that's impossible, because I cannot enforce regex 1 to apply before regex 2.

Could you find a way to manage this precedence? For example by adding an optional "regexOrder" property?

**Comment by fabiospampinato** [comment]
> because of the unordered object properties in JS, I guess

Access order of object properties isn't guaranteed by the spec, but effectively V8 returns them in order, and I don't think this is going to change because of backwards compatibility.

The problem here is rather that VSC doesn't really support having multiple decorators for the same text, you'll have to make your regexes more specific in order to avoid conflicts between them, for example you should use negative lookaheads (`(?!")`), possibly negative lookbehinds also (I don't remember if those are supproted by VSC currently (`(?<!")`).
