### ISSUE TITLE
Decoration extends after the match

### ISSUE THREAD

**Issue by rolandleth** [fabiospampinato/vscode-highlight#31]
Hello again 😀

Even for the simplest regex and option, the decoration continues until I press enter. Screenshots didn't capture the caret, but it's obvious which is which :)

<img width="168" alt="CleanShot 2019-04-09 at 16 31 06@2x" src="https://user-images.githubusercontent.com/1858700/55804483-063a3780-5ae5-11e9-96d8-f90fa2b24ff7.png">
<img width="135" alt="CleanShot 2019-04-09 at 16 33 47@2x" src="https://user-images.githubusercontent.com/1858700/55804585-47324c00-5ae5-11e9-86d1-81c15802c9ef.png">
<img width="130" alt="CleanShot 2019-04-09 at 16 33 51@2x" src="https://user-images.githubusercontent.com/1858700/55804588-48637900-5ae5-11e9-8a82-cd009dabba95.png">

Thank you!

**Comment by rolandleth** [comment]
I know the pain of maintaining an open source library and I'd love to help, but I have zero experience with VSC extensions. Will try to have a look over the code in the weekend, but ... I don't have high hopes 😞

Thanks for the quick replies!

**Comment by rolandleth** [comment]
Any tips on where/how to start debugging this? I'd like to give it a shot today.

**Comment by fabiospampinato** [comment]
@rolandleth All the logic involving decorating the document is [here](https://github.com/fabiospampinato/vscode-highlight/blob/master/src%2Fdecorator.ts), since this happens when editing a single line I think [this](https://github.com/fabiospampinato/vscode-highlight/blob/8c3d0a26645a48888af08dd054c6938c23b8a38a/src/decorator.ts#L193) function is responsible for the issue, I think maybe at some point there it decides that nothing changed and it [exits](https://github.com/fabiospampinato/vscode-highlight/blob/8c3d0a26645a48888af08dd054c6938c23b8a38a/src/decorator.ts#L241).

**Comment by rolandleth** [comment]
Awesome, thanks!

**Comment by rolandleth** [comment]
I identified — I think and hope — the issue [here](https://github.com/fabiospampinato/vscode-highlight/blob/8c3d0a26645a48888af08dd054c6938c23b8a38a/src/decorator.ts#L175). 

Typing `==` goes beyond that line, but every character after — until there's a new match — returns there. Forcing the pass beyond would defeat the whole purpose of the statement, but I think making it pass just once — after the first character typed after a match — would be enough.

Any suggestions? I'm slightly lost; the statement is rather complicated.

**Comment by fabiospampinato** [comment]
Ok I think I know what's going on, by default we are setting a [range behavior](https://code.visualstudio.com/api/references/vscode-api#DecorationRangeBehavior) of 3 (Left Closed - Right Open), which means that decorations should by default extend to the right but not to the left, the point of this is that if the whole line needs to be decorated (think about a todo comment perhaps), and you're currently writing the line, you want the thing to be decorated immediately, and not see each individual character getting decorated only after this extension kicks-in.

Setting a range behavior of 1 (Left Closed - Right Closed) solves your specific problem:

```
    "(===)": {
      "decorations": {
        "color": "red",
        "rangeBehavior": 1
      }
    },
```

So I think the problem should be approached this way:

- For the best experience, you should add `"rangeBehavior": 1` to your decorator, otherwise for a brief moment you may see the following character getting decorated too.

- We should still eventually decorate the document properly, so I think that `if` expression you linked needs to get a bit more complicated: other than checking if the decorations on that line remained the same we also have to check if the next line's length is greater than the previous line's length + 1, or the length didn't change, basically if there's one extra character after the decoration we should also re-decorate, to account for possible range behaviors that tell the decorations to extend to the right.

**Comment by rolandleth** [comment]
Yupp, that solved my particular issue, thank you!

I did try to find a way to do that check, but I can't find anything on `doc` or `textEditor` that would give us the current line, to get its length. I suppose we'd have to store it in a property when the decoration happens, then compare that in that `if` with the current line length.

**Comment by fabiospampinato** [comment]
It sounds tricky or expensive to do, I'll try to fix this when I'll get some time.

**Comment by rolandleth** [comment]
Awesome 💪🏻

Have a great Saturday, Fabio!

**Comment by fabiospampinato** [comment]
Thanks, you too 😄
